"""Export system constitutions for the A2A Software Factory."""

from .constitutions import (
    FOCAL_COORDINATOR_CONSTITUTION,
    GCLOUD_READONLY_PROBE_CONSTITUTION,
    SHARED_CONSTITUTION_PRINCIPLES,
    SOFTWARE_BUILDER_CONSTITUTION,
    WIF_GIT_DELIVERY_CONSTITUTION,
    WORKSPACE_ARCHITECT_CONSTITUTION,
)

__all__ = [
    "FOCAL_COORDINATOR_CONSTITUTION",
    "GCLOUD_READONLY_PROBE_CONSTITUTION",
    "SHARED_CONSTITUTION_PRINCIPLES",
    "SOFTWARE_BUILDER_CONSTITUTION",
    "WIF_GIT_DELIVERY_CONSTITUTION",
    "WORKSPACE_ARCHITECT_CONSTITUTION",
]
